'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class App_Listado_CobrosPendientes
    Public Property PedidoId As Integer
    Public Property ClienteId As Nullable(Of Integer)
    Public Property cliente As String
    Public Property PersonalId As Nullable(Of Integer)
    Public Property vendedor As String
    Public Property FechaPedido As Nullable(Of Date)
    Public Property totalfactura As Nullable(Of Decimal)
    Public Property pendiente As Nullable(Of Decimal)

End Class
