
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class EmpresaReporte

    Public Property Id As Integer

    Public Property EmpresaId As Integer

    Public Property ReporteId As Integer

    Public Property NombreReporte As String

    Public Property ReporteTipoId As Integer

    Public Property NombreTipo As String

    Public Property Estado As Integer

    Public Property TipoReporte As Integer

    Public Property Descripcion As String

    Public Property Descripcion1 As String

    Public Property Descripcion2 As String



    Public Overridable Property Empresa As Empresa


End Class
