'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reporte_KardexGeneral
    Public Property canumi As Integer
    Public Property cacod As String
    Public Property cadesc As String
    Public Property Descripcion As String
    Public Property Categoria As String
    Public Property SaldoAnterior As String
    Public Property Entradas As String
    Public Property Salidas As String
    Public Property SaldoFinal As String

End Class
