'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sucursales
    Public Property Id As Integer
    Public Property NombreAlmacen As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Latitud As Nullable(Of Decimal)
    Public Property Longitud As Nullable(Of Decimal)

End Class
