'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0014
    Public Property cqnumi As Integer
    Public Property cqprod As Nullable(Of Integer)
    Public Property cqcomision As Nullable(Of Decimal)
    Public Property cqcomisionRep As Nullable(Of Decimal)
    Public Property cqestado As Nullable(Of Integer)
    Public Property cqfact As Nullable(Of Date)
    Public Property cqhact As String
    Public Property cquact As String

End Class
