
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC004C

    Public Property cccnumi As Integer

    Public Property cccnumi4 As Nullable(Of Integer)

    Public Property cccfrecvisita As Nullable(Of Integer)

    Public Property ccclunes As Nullable(Of Boolean)

    Public Property cccmartes As Nullable(Of Boolean)

    Public Property cccmiercoles As Nullable(Of Boolean)

    Public Property cccjueves As Nullable(Of Boolean)

    Public Property cccviernes As Nullable(Of Boolean)

    Public Property cccsabado As Nullable(Of Boolean)

    Public Property cccdomingo As Nullable(Of Boolean)

    Public Property cccfechaprox As Nullable(Of Date)

    Public Property cccfact As Nullable(Of Date)

    Public Property ccchact As String

    Public Property cccuact As String


End Class
