'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0001
    Public Property cccnumi As Nullable(Of Integer)
    Public Property cccmapa As Nullable(Of Integer)
    Public Property cccnotiped As Nullable(Of Integer)
    Public Property cccvcre As Nullable(Of Integer)
    Public Property cccvdes As Nullable(Of Integer)
    Public Property cccvccli As Nullable(Of Integer)
    Public Property cccvacu As Nullable(Of Integer)
    Public Property cccftp As Nullable(Of Integer)
    Public Property cccvcre2 As Nullable(Of Integer)
    Public Property cccmprec As Nullable(Of Integer)
    Public Property cccadev As Nullable(Of Integer)
    Public Property ccprecapp As Nullable(Of Integer)
    Public Property ccstock As Nullable(Of Integer)
    Public Property cccdespacho As Nullable(Of Integer)
    Public Property cccubilogo As String
    Public Property cccfrecvisita As Integer
    Public Property cccCRM As Nullable(Of Integer)

End Class
