'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC012
    Public Property cenumi As Integer
    Public Property cedesc As String
    Public Property cecon1 As String
    Public Property cecon2 As String
    Public Property cecon3 As String
    Public Property cecon4 As String

End Class
