
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP0091

    Public Property pnnumi As Integer

    Public Property pncprod As String

    Public Property pnpcant As Nullable(Of Decimal)

    Public Property pnpbase As Nullable(Of Decimal)

    Public Property pnptot As Nullable(Of Decimal)

    Public Property pndesc As Nullable(Of Decimal)

    Public Property pntotal As Nullable(Of Decimal)

    Public Property pnfamilia As Nullable(Of Integer)

    Public Property pncampo1 As Nullable(Of Integer)

    Public Property pncampo2 As Nullable(Of Decimal)


End Class
