'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP009
    Public Property pmnumi As Integer
    Public Property pmfdoc As Nullable(Of Date)
    Public Property pmhora As String
    Public Property pmccli As Nullable(Of Integer)
    Public Property pmzona As Nullable(Of Integer)
    Public Property pmrepa As Nullable(Of Integer)
    Public Property pmobs As String
    Public Property pmobs2 As String
    Public Property pmest As Nullable(Of Integer)
    Public Property pmap As Nullable(Of Integer)
    Public Property pmpg As Nullable(Of Integer)
    Public Property pmfact As Nullable(Of Date)
    Public Property pmhact As String
    Public Property pmuact As String

End Class
