
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Visita

    Public Property Id As Integer

    Public Property RepartidorId As Nullable(Of Integer)

    Public Property PedidoId As Nullable(Of Integer)

    Public Property ClienteId As Nullable(Of Integer)

    Public Property Descripcion As String

    Public Property Estado As Nullable(Of Integer)

    Public Property Latitud As Nullable(Of Decimal)

    Public Property Longitud As Nullable(Of Decimal)

    Public Property Fecha As Nullable(Of Date)

    Public Property Hora As String

    Public Property IdSincronizacion As String


End Class
