'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_EstadoCuentasClientes
    Public Property numicliente As Nullable(Of Integer)
    Public Property cliente As String
    Public Property fecha As String
    Public Property numiDoc As Integer
    Public Property Detalle As String
    Public Property fechacredito As String
    Public Property Importe As Nullable(Of Decimal)
    Public Property Pagos As Nullable(Of Decimal)
    Public Property Saldos As Decimal
    Public Property concepto As Integer
    Public Property fecha1 As String

End Class
