
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_MorosidadProveedores

    Public Property Numiprov As Nullable(Of Integer)

    Public Property Prov As String

    Public Property Numicompra As Integer

    Public Property Fechacompra As String

    Public Property Fechacredito As String

    Public Property TotalCompra As Nullable(Of Decimal)

    Public Property Pagos As Nullable(Of Decimal)

    Public Property Saldo As Nullable(Of Decimal)

    Public Property Mora As Nullable(Of Integer)


End Class
