
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_Proforma

    Public Property pmnumi As Integer

    Public Property pmfdoc As Nullable(Of Date)

    Public Property ccdesc As String

    Public Property ccnomfac As String

    Public Property ccdirec As String

    Public Property canumi As Integer

    Public Property cadesc As String

    Public Property pmobs As String

    Public Property pnpcant As Nullable(Of Decimal)

    Public Property pnpbase As Nullable(Of Decimal)

    Public Property pnptot As Nullable(Of Decimal)

    Public Property pndesc As Nullable(Of Decimal)

    Public Property pntotal As Nullable(Of Decimal)

    Public Property pmest As Nullable(Of Integer)

    Public Property Total As Nullable(Of Decimal)

    Public Property ccnit As String

    Public Property cctelf1 As String

    Public Property cedesc As String


End Class
