'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_VentasComision
    Public Property codven As Integer
    Public Property vendedor As String
    Public Property cacat As Nullable(Of Integer)
    Public Property categoria As String
    Public Property numiProd As Integer
    Public Property cacod As String
    Public Property producto As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property obpbase As Nullable(Of Decimal)
    Public Property TotalVenta As Nullable(Of Decimal)
    Public Property cqcomision As Nullable(Of Decimal)
    Public Property mcomision As Nullable(Of Decimal)

End Class
