
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_VisitaClientes

    Public Property ccnumi As Integer

    Public Property cccod As String

    Public Property ccdesc As String

    Public Property ccdirec As String

    Public Property cctelf1 As String

    Public Property cctelf2 As String

    Public Property ccultped As Nullable(Of Date)

    Public Property ccultvent As Nullable(Of Date)

    Public Property dias As Nullable(Of Integer)


End Class
